INSERT INTO exercise (id, name, primary_muscle, secondary_muscle, equipment, exercise_animation) VALUES
-- CHEST (15)
(gen_random_uuid(), 'Barbell Bench Press', 'CHEST', 'TRICEPS', 'BARBELL', NULL),
(gen_random_uuid(), 'Incline Barbell Bench Press', 'CHEST', 'SHOULDERS', 'BARBELL', NULL),
(gen_random_uuid(), 'Decline Barbell Bench Press', 'CHEST', 'TRICEPS', 'BARBELL', NULL),
(gen_random_uuid(), 'Dumbbell Bench Press', 'CHEST', 'TRICEPS', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Incline Dumbbell Press', 'CHEST', 'SHOULDERS', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Decline Dumbbell Press', 'CHEST', 'TRICEPS', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Push-Up', 'CHEST', 'TRICEPS', 'NONE', NULL),
(gen_random_uuid(), 'Chest Fly Machine', 'CHEST', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Dumbbell Fly', 'CHEST', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Incline Dumbbell Fly', 'CHEST', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Cable Crossover', 'CHEST', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Pec Deck', 'CHEST', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Squeeze Press', 'CHEST', 'TRICEPS', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Dips for Chest', 'CHEST', 'TRICEPS', 'NONE', NULL),
(gen_random_uuid(), 'Resistance Band Chest Press', 'CHEST', NULL, 'RESISTANCE_BAND', NULL),

-- BACK (15)
(gen_random_uuid(), 'Pull-Up', 'LATS', 'BICEPS', 'NONE', NULL),
(gen_random_uuid(), 'Chin-Up', 'LATS', 'BICEPS', 'NONE', NULL),
(gen_random_uuid(), 'Lat Pulldown', 'LATS', 'BICEPS', 'MACHINE', NULL),
(gen_random_uuid(), 'Close-Grip Lat Pulldown', 'LATS', 'BICEPS', 'MACHINE', NULL),
(gen_random_uuid(), 'Barbell Row', 'UPPER_BACK', 'BICEPS', 'BARBELL', NULL),
(gen_random_uuid(), 'T-Bar Row', 'UPPER_BACK', 'BICEPS', 'BARBELL', NULL),
(gen_random_uuid(), 'Dumbbell Row', 'UPPER_BACK', 'BICEPS', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Seated Row Machine', 'UPPER_BACK', 'BICEPS', 'MACHINE', NULL),
(gen_random_uuid(), 'Face Pull', 'UPPER_BACK', 'SHOULDERS', 'RESISTANCE_BAND', NULL),
(gen_random_uuid(), 'Inverted Row', 'UPPER_BACK', 'BICEPS', 'NONE', NULL),
(gen_random_uuid(), 'Shrug with Barbell', 'TRAPS', NULL, 'BARBELL', NULL),
(gen_random_uuid(), 'Shrug with Dumbbells', 'TRAPS', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Deadlift', 'FULL_BODY', 'LOWER_BACK', 'BARBELL', NULL),
(gen_random_uuid(), 'Rack Pull', 'LOWER_BACK', 'TRAPS', 'BARBELL', NULL),
(gen_random_uuid(), 'Good Morning', 'LOWER_BACK', 'HAMSTRINGS', 'BARBELL', NULL),

-- SHOULDERS (15)
(gen_random_uuid(), 'Barbell Overhead Press', 'SHOULDERS', 'TRICEPS', 'BARBELL', NULL),
(gen_random_uuid(), 'Seated Dumbbell Shoulder Press', 'SHOULDERS', 'TRICEPS', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Arnold Press', 'SHOULDERS', 'TRICEPS', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Push Press', 'SHOULDERS', 'TRICEPS', 'BARBELL', NULL),
(gen_random_uuid(), 'Lateral Raise', 'SHOULDERS', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Front Raise', 'SHOULDERS', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Barbell Upright Row', 'SHOULDERS', 'TRAPS', 'BARBELL', NULL),
(gen_random_uuid(), 'Dumbbell Upright Row', 'SHOULDERS', 'TRAPS', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Machine Shoulder Press', 'SHOULDERS', 'TRICEPS', 'MACHINE', NULL),
(gen_random_uuid(), 'Resistance Band Overhead Press', 'SHOULDERS', NULL, 'RESISTANCE_BAND', NULL),
(gen_random_uuid(), 'Face Pull with Bands', 'SHOULDERS', 'UPPER_BACK', 'RESISTANCE_BAND', NULL),
(gen_random_uuid(), 'Plate Front Raise', 'SHOULDERS', NULL, 'PLATE', NULL),
(gen_random_uuid(), 'Handstand Push-Up', 'SHOULDERS', 'TRICEPS', 'NONE', NULL),
(gen_random_uuid(), 'Rear Delt Fly Machine', 'SHOULDERS', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Bent Over Rear Delt Raise', 'SHOULDERS', NULL, 'DUMBBELL', NULL),

-- ARMS (20: Biceps + Triceps + Forearms)
(gen_random_uuid(), 'Barbell Curl', 'BICEPS', NULL, 'BARBELL', NULL),
(gen_random_uuid(), 'Dumbbell Curl', 'BICEPS', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Hammer Curl', 'BICEPS', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Preacher Curl', 'BICEPS', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Incline Dumbbell Curl', 'BICEPS', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Concentration Curl', 'BICEPS', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Cable Curl', 'BICEPS', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Overhead Dumbbell Extension', 'TRICEPS', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Skull Crusher', 'TRICEPS', NULL, 'BARBELL', NULL),
(gen_random_uuid(), 'Tricep Pushdown', 'TRICEPS', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Close-Grip Bench Press', 'TRICEPS', 'CHEST', 'BARBELL', NULL),
(gen_random_uuid(), 'Dips for Triceps', 'TRICEPS', NULL, 'NONE', NULL),
(gen_random_uuid(), 'Kickback', 'TRICEPS', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Reverse Curl', 'FOREARMS', 'BICEPS', 'BARBELL', NULL),
(gen_random_uuid(), 'Wrist Curl', 'FOREARMS', NULL, 'BARBELL', NULL),
(gen_random_uuid(), 'Reverse Wrist Curl', 'FOREARMS', NULL, 'BARBELL', NULL),
(gen_random_uuid(), 'Farmer Carry Dumbbells', 'FOREARMS', NULL, 'DUMBBELL', NULL),
(gen_random_uuid(), 'Plate Pinch Hold', 'FOREARMS', NULL, 'PLATE', NULL),
(gen_random_uuid(), 'Zottman Curl', 'BICEPS', 'FOREARMS', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Overhead Rope Extension', 'TRICEPS', NULL, 'MACHINE', NULL),

-- LEGS (25: Quads, Hamstrings, Glutes, Calves, Adductors, Abductors)
(gen_random_uuid(), 'Back Squat', 'QUADRICEPS', 'GLUTES', 'BARBELL', NULL),
(gen_random_uuid(), 'Front Squat', 'QUADRICEPS', 'GLUTES', 'BARBELL', NULL),
(gen_random_uuid(), 'Goblet Squat', 'QUADRICEPS', 'GLUTES', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Leg Press', 'QUADRICEPS', 'GLUTES', 'MACHINE', NULL),
(gen_random_uuid(), 'Walking Lunge', 'QUADRICEPS', 'GLUTES', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Bulgarian Split Squat', 'QUADRICEPS', 'GLUTES', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Step-Up with Dumbbells', 'QUADRICEPS', 'GLUTES', 'DUMBBELL', NULL),
(gen_random_uuid(), 'Romanian Deadlift', 'HAMSTRINGS', 'GLUTES', 'BARBELL', NULL),
(gen_random_uuid(), 'Stiff-Leg Deadlift', 'HAMSTRINGS', NULL, 'BARBELL', NULL),
(gen_random_uuid(), 'Leg Curl Machine', 'HAMSTRINGS', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Hip Thrust', 'GLUTES', 'HAMSTRINGS', 'BARBELL', NULL),
(gen_random_uuid(), 'Glute Bridge', 'GLUTES', NULL, 'NONE', NULL),
(gen_random_uuid(), 'Cable Kickback', 'GLUTES', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Standing Calf Raise', 'CALVES', NULL, 'NONE', NULL),
(gen_random_uuid(), 'Seated Calf Raise', 'CALVES', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Donkey Calf Raise', 'CALVES', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Side Lying Leg Lift', 'ABDUCTORS', NULL, 'NONE', NULL),
(gen_random_uuid(), 'Cable Abduction', 'ABDUCTORS', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Seated Abduction Machine', 'ABDUCTORS', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Adduction Machine', 'ADDUCTORS', NULL, 'MACHINE', NULL),
(gen_random_uuid(), 'Sumo Deadlift', 'HAMSTRINGS', 'GLUTES', 'BARBELL', NULL),
(gen_random_uuid(), 'Kettlebell Goblet Squat', 'QUADRICEPS', 'GLUTES', 'KETTLEBELL', NULL),
(gen_random_uuid(), 'Box Jump', 'QUADRICEPS', 'CALVES', 'NONE', NULL),
(gen_random_uuid(), 'Sled Push', 'FULL_BODY', 'QUADRICEPS', 'OTHER', NULL),
(gen_random_uuid(), 'Split Squat Jumps', 'QUADRICEPS', 'CALVES', 'NONE', NULL);
